name: match_cafe
description: Match Cafe mobile application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+10

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  agora_rtc_engine: ^4.0.2
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  eventify: ^0.1.4
  executor: ^2.2.0
  firebase_auth: ^1.3.0
  firebase_core: ^1.2.1
  firebase_database: ^7.1.1
  firebase_messaging: ^10.0.2
  firebase_remote_config: ^0.10.0+2
  firebase_storage: ^8.1.1
  floating_bottom_navigation_bar: ^1.5.1
  flutter_local_notifications: ^6.0.0
  flutter_secure_storage: ^4.2.0
  flutter_webrtc: ^0.6.4
  grouped_list: ^4.0.0
  image_cropper: ^1.4.0
  image_picker: ^0.8.0+3
  json_annotation:
  logging: ^1.0.1
  material_floating_search_bar: ^0.3.4
  permission_handler: ^8.0.1
  provider: ^5.0.0
  retrofit: ^2.0.0
  timeline_tile: ^2.0.0
  url_launcher: ^6.0.6
  firebase_dynamic_links: ^2.0.6
  share: ^2.0.4
  move_to_background:
  flutter_ion:
    git:
      url: git://github.com/pion/ion-sdk-flutter.git
  uuid: ^3.0.4
  html: ^0.15.0
  webview_flutter: ^2.0.9
  flutter_inappwebview: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  retrofit_generator: ^2.0.0+1

flutter:
  uses-material-design: true

  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product_Sans_Regular.ttf
        - asset: assets/fonts/Product_Sans_Bold.ttf
          weight: 700
        - asset: assets/fonts/Product_Sans_Italic.ttf
          style: italic
  assets:
    - assets/images/
